name: Deploy to Branch

on:
  push:
    branches:
      - develop-ikura  # ビルドをトリガーするブランチ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Deploy to branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Deploy to branch'
        git push origin HEAD:sandbox  # ここで指定したブランチにプッシュ
